services:
  nx-ai:
    build:
      context: .
      target: dev
    env_file:
      - ./.env
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspaces/nx-ai
      - ./venv:/app/venv:ro

