import os
from github import Github, Auth

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")


def create_pull_request_on_github(filename: str):
    auth = Auth.Token(GITHUB_TOKEN)
    g = Github(auth=auth)
    
    repo = g.get_organization("nx-academy").get_repo("nx-academy.github.io")
    sb = repo.get_branch("main")
    
    print("====")
    print(filename)
    print("====")
    
    # Quiz logic for now
    repo.create_git_ref(ref=f"refs/heads/ai_{filename}-quiz", sha=sb.commit.sha)
    print(f"Successfully created branch ai_{filename}-quiz")
    
    with open(f"nx_ai/quizzes_data/{filename}.json", "r", 
              encoding="utf-8") as f:
        content = f.read()
        
        # If the file already exists, it will throw an errors
        repo.create_file(
            path=f"public/quiz/toto.json",
            message=f"Ajout du quiz {filename}",
            content=content,
            branch=f"ai_{filename}-quiz"
        )
        print(f"Successfully commit {filename}.json file")
        
        repo.create_pull(
            base="main",
            title=f"(IA): Adding {filename} quiz",
            body="Autogenerated content for quiz",
            head=f"ai_{filename}-quiz"
        )
        print(f"Successfully create the PR")
    
    g.close()
