name: Build and Push Docker Image to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Build and Deploy to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building then pushing the image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nx-ai:latest
